services:
  mysql:
    image: mysql:8.0
    container_name: mysql_sent
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sent_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:6.0
    container_name: mongodb_sent
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sent_net

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq_sent
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - sent_net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  sent_server:
    image: ldhbenecia/sent-app:latest
    container_name: sent_server
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    expose:
      - "8080"
    networks:
      - sent_net
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - /home/ubuntu/certs/devcerts:/etc/certs:ro
    command: /bin/sh -c "envsubst '$${DOMAIN_NAME} $${BACKEND_SERVICE} $${BACKEND_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - sent_server
    networks:
      - sent_net

volumes:
  mysql_data:
  rabbitmq-data:
  mongodb_data:

networks:
  sent_net:
    driver: bridge
